### ISSUE TITLE
SOW - Area for github and issue tracking?

### ISSUE THREAD

**Issue by bob-moore** [RCS337/HollyHotel#1]
I'm not sure where to put it in the SOW, but I though we should have something about version control / git and possibly about using THIS issue tracking area for any issues we know we want documented.

**Comment by pharsh** [comment]
Sorry, I am more of a morning person, and crashed shortly after sending out my email last night.  I streamlined a little of what you put out there (basically removed what I had there as it became redundant with what you had added under technology).    I didn't add any more right now, but I will come back to it later when I can find some time (and if it still has holes).
 As far as this comment, using this area, I would add the use of this tool under the teamwork section.

**Comment by bob-moore** [comment]
I've never used the issue tracking here on github before. I wanted to put a comment _on here_ to kinda get a feel for how it works. If nothing else, it's an easy place to track issues as to make sure they are not forgotten about, and we can use it like a "check list" of known issues before signing off. But it's not something I have any interest in forcing anyone to use.

Yeah...morning and night. Went to bed at 3:30, got back up at 6. That's pretty much my schedule. Got I wish kids didn't get up so bloody early. I'm marking this as closed. I just wanted to put it here instead of an email or something, just to see how it works.
