### ISSUE TITLE
Reservation Info View

### ISSUE THREAD

**Issue by bob-moore** [RCS337/HollyHotel#2]
Getting error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'RoomID' in 'order clause'

for query: SELECT ReservationID, ParentResID, BillToID, BillToFirstName, BillToLastName, GuestID, GuestFirstName, GuestLastName, EventID, EventName, HostID, HostFirstName, HostLastName, RoomType, RoomTypeName, StartDate, EndDate, Rate, Deposit, RoomID, Smoking, ConvertedToStay, Features, Feature_Description FROM reservationinfovw

**Comment by pharsh** [comment]
Not sure what version you are using, as I am not seeing the issue.  just uploaded it again in update.sql

**Comment by bob-moore** [comment]
Updated, still getting same error. Error occurs in Workbench, SQL Pro, and in application (PHP)

**Comment by pharsh** [comment]
Update just sent.  It was in the embedded view that your system did not like the order by . .. removed it
